### ISSUE TITLE
The following error is reported when the docker compose build is executed

### ISSUE THREAD

**Issue by chatterzhao** [beowulf1416/saas#9]
#0 569.3 error: visibility `pub` is not followed by an item
#0 569.3   --> data/pg/src/inventory/item.rs:75:5
#0 569.3    |
#0 569.3 75 |     pub async update(
#0 569.3    |     ^^^ the visibility
#0 569.3    |
#0 569.3    = help: you likely meant to define an item, e.g., `pub fn foo() {}`
#0 569.3 

#0 569.3 error: non-item in item list
#0 569.3    --> data/pg/src/inventory/item.rs:75:9
#0 569.3     |
#0 569.3 24  | impl Item {
#0 569.3     |           - item list starts here
#0 569.3 ...
#0 569.3 75  |     pub async update(
#0 569.3     |         ^^^^^ non-item starts here
#0 569.3 ...
#0 569.3 135 | }
#0 569.3     | - item list ends here
#0 569.3 

#0 569.4 error[E0412]: cannot find type `ItemBalances` in this scope
#0 569.4   --> data/pg/src/inventory/item_balances.rs:24:6
#0 569.4    |
#0 569.4 24 | impl ItemBalances {
#0 569.4    |      ^^^^^^^^^^^^ not found in this scope
#0 569.4 

#0 569.7 error[E0308]: mismatched types
#0 569.7   --> data/pg/src/inventory/item_balances.rs:40:17
#0 569.7    |
#0 569.7 40 |                 &quantity
#0 569.7    |                 ^^^^^^^^^ expected struct `Uuid`, found `f32`
#0 569.7    |
#0 569.7    = note: expected reference `&&Uuid`
#0 569.7               found reference `&&f32`
#0 569.7 

#0 569.7 error: the `Self` constructor can only be used with tuple or unit structs
#0 569.7   --> data/pg/src/inventory/item_balances.rs:26:16
#0 569.7    |
#0 569.7 26 |         return Self(Dbo::new(client));
#0 569.7    |                ^^^^
#0 569.7 

#0 569.7 Some errors have detailed explanations: E0308, E0412.
#0 569.7 For more information about an error, try `rustc --explain E0308`.
#0 569.7 warning: `pg` (lib) generated 36 warnings
#0 569.7 error: could not compile `pg` due to 5 previous errors; 36 warnings emitted
#0 569.7 warning: build failed, waiting for other jobs to finish...
#0 573.8 error: failed to compile `api v0.1.0 (/opt/ideas/api)`, intermediate artifacts can be found at `/opt/ideas/target`
------
failed to solve: executor failed running [/bin/sh -c cargo install --root /opt/ideas --path api]: exit code: 101

**Comment by beowulf1416** [comment]
I checked it out and docker-compose build works for me. I might have fixed it already here - https://github.com/beowulf1416/idEAS/commit/669be9309673e95289823c70c5de12e78de5d852
